spring.application.name=SE2034-SWP391-G4
server.port=8080 
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ElearningPlatform;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
server.servlet.session.persistent=false

# Open Session In View (OSIV)

# ===============================
# Hibernate ddl-auto options
# ===============================

# none
# Không làm gì với database
# → dùng khi bạn tự quản lý schema bằng SQL hoặc tool ngoài
#spring.jpa.hibernate.ddl-auto=none

# validate
# Chỉ kiểm tra DB có khớp với Entity không
# → nếu sai sẽ lỗi khi start app
# → dùng cho production (an toàn)
#spring.jpa.hibernate.ddl-auto=validate

# update
# Tự động cập nhật database theo Entity
# → tạo bảng nếu chưa có
# → thêm cột mới
# → KHÔNG xóa dữ liệu
# → KHÔNG rename chuẩn
# → dùng khi develop
#spring.jpa.hibernate.ddl-auto=update

# create
# Xóa toàn bộ bảng cũ → tạo lại từ đầu
# → MẤT HẾT DỮ LIỆU
# → dùng khi test nhanh / demo
#spring.jpa.hibernate.ddl-auto=create

# create-drop
# Tạo DB khi start app
# Xóa DB khi stop app
# → dùng cho unit test
#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
